name: Generate Test Vectors
on:
  push:
    branches:
      - master
jobs:
  generate:
    name: Generate all test vectors, updating existing vectors IF they have changed.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Init submodules
        run: git submodule update --init
      - name: Build filecoin-ffi
        run: cd gen/extern/filecoin-ffi && make
      - name: Update Test Vectors
        run: make upgen
      - name: Commit and Push Updated Test Vectors
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update test vectors'
          branch: chore/update-test-vectors-${{ github.head_ref }}
          file_pattern: corpus/**/*.json
