name: Generate Test Vectors
on:
  push:
    branches:
      - master
jobs:
  update-vectors:
    name: Update test vectors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - name: Build filecoin-ffi
        run: cd gen/extern/filecoin-ffi && make
      - name: Fetch go dependencies
        run: go get ./...
      - name: Update test vectors
        run: make upgen
      - name: Commit and push
        run: |
          git checkout -b chore/update-test-vectors-${{ github.sha }}
          git add corpus/**/*.json
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "chore: update test vectors"
          git push origin chore/update-test-vectors-${{ github.sha }}
